---

- name: install python-setuptools
  apt:
    name: python-setuptools
    state: present

- name: install pip for docker-compose installation
  easy_install:
    name: pip
    state: latest

- name: install docker-compose
  pip:
    name: docker-compose
    state: latest
