---

- name: Test Architecture
  assert:
    that:
      - "ansible_architecture == 'x86_64'"
    msg: "Architecture must be x86_64."

- name: Test Distribution Release
  assert:
    that:
      - "ansible_distribution_release == 'xenial'"
    msg: "Distribution must be Ubuntu Xenial"

- name: Include vars
  include_vars: "{{ ansible_distribution }}.yml"

- name: ensure Docker GPG key is present
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"

- name: install docker dependency packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ docker_dependency_packages }}"

- apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: 'docker'

- name: install docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ docker_packages }}"

- name: start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Import compose.yml
  import_tasks: compose.yml

- name: Import tests.yml
  import_tasks: tests.yml
  when: 
    - tests_enabled
